import { beforeEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
import type { AdminUser } from '@/types'

const mocks = vi.hoisted(() => ({ get: vi.fn(), candidates: vi.fn(), save: vi.fn(), reset: vi.fn(), activate: vi.fn(), success: vi.fn(), error: vi.fn() }))
vi.mock('@/api/modelPolicy', async () => {
  const actual = await vi.importActual<typeof import('@/api/modelPolicy')>('@/api/modelPolicy')
  return { ...actual, getUserModelPolicy: mocks.get, getModelPolicyCandidates: mocks.candidates, saveUserModelPolicy: mocks.save, resetUserModelQuota: mocks.reset, activateUserModelPolicies: mocks.activate }
})
vi.mock('vue-i18n', async () => ({ ...await vi.importActual<typeof import('vue-i18n')>('vue-i18n'), useI18n: () => ({ t: (key: string) => key }) }))
vi.mock('@/stores/app', () => ({ useAppStore: () => ({ showInfo: vi.fn(), showError: mocks.error, showSuccess: mocks.success, showWarning: vi.fn() }) }))
vi.mock('@/components/common/BaseDialog.vue', () => ({ default: { props: ['show'], template: '<div v-if="show"><slot/><slot name="footer"/></div>' } }))
vi.mock('@/components/common/ConfirmDialog.vue', () => ({ default: { props: ['show', 'message'], emits: ['confirm', 'cancel'], template: '<div v-if="show" data-test="confirm"><p>{{message}}</p><button @click="$emit(\'confirm\')">confirm</button></div>' } }))
import UserModelPolicyModal from '../UserModelPolicyModal.vue'
import Select from '@/components/common/Select.vue'

const initial = () => ({ enabled: false, revision: 4, rules: [{ model: 'gpt-5.6-sol', mode: 'limited', request_limit: 3, window_hours: 6, window_mode: 'hours' }], windows: [] })
beforeEach(() => { vi.clearAllMocks(); mocks.get.mockResolvedValue(initial()); mocks.candidates.mockResolvedValue(['gpt-5.6-luna', 'gpt-5.6-sol']); mocks.save.mockResolvedValue({ ...initial(), revision: 5 }) })

describe('user model rules editor', () => {
  it('keeps an inline checklist without floating tags or changing hints when selecting all', async () => {
    const models = Array.from({ length: 80 }, (_, i) => `model-${i}`)
    mocks.get.mockResolvedValue({ ...initial(), rules: [] })
    mocks.candidates.mockResolvedValue(models)
    const w = mount(UserModelPolicyModal, { props: { show: true, user: { id: 7 } as AdminUser } })
    await flushPromises()
    const checklist = w.get('[data-testid="model-checklist"]')
    const hint = w.get('[data-testid="bulk-model-form"] p')
    const hintText = hint.text()
    expect(checklist.classes()).toContain('h-56')
    for (let i = 0; i < 3; i++) {
      await w.get('[data-testid="select-visible-models"]').trigger('click')
      await flushPromises()
      expect(w.findAll('input[type="checkbox"]').every(input => (input.element as HTMLInputElement).checked)).toBe(true)
      expect(w.get('[data-testid="model-checklist"]').element).toBe(checklist.element)
      expect(hint.text()).toBe(hintText)
      expect(w.find('[data-testid="toggle-model-dropdown"]').exists()).toBe(false)
      expect(w.find('[data-testid="pending-selection"]').exists()).toBe(false)
      expect(w.get('button[form="user-model-policy-form"]').attributes('disabled')).toBeDefined()
      await w.get('[data-testid="clear-model-selection"]').trigger('click')
      expect(w.findAll('input[type="checkbox"]').every(input => !(input.element as HTMLInputElement).checked)).toBe(true)
      expect(w.get('button[form="user-model-policy-form"]').attributes('disabled')).toBeUndefined()
      expect(hint.text()).toBe(hintText)
    }
    expect(mocks.get).toHaveBeenCalledTimes(1)
    expect(mocks.candidates).toHaveBeenCalledTimes(1)
    expect(mocks.save).not.toHaveBeenCalled()
  })
  it('selects only search results, keeps hidden checks, and never submits on search Enter', async () => {
    mocks.candidates.mockResolvedValue(['gpt-5.6-luna', 'gpt-5.6-sol', 'gpt-6-astra'])
    const w = mount(UserModelPolicyModal, { props: { show: true, user: { id: 7 } as AdminUser } })
    await flushPromises()
    expect(w.find('input[type="checkbox"][value="gpt-5.6-sol"]').exists()).toBe(false)
    const search = w.get('[data-testid="bulk-model-search"]')
    await search.setValue(' LUNA ')
    await w.get('[data-testid="select-visible-models"]').trigger('click')
    await search.setValue('astra')
    await w.get('[data-testid="select-visible-models"]').trigger('click')
    await w.get('[data-testid="select-visible-models"]').trigger('click')
    await search.trigger('keydown', { key: 'Enter' })
    expect(w.findAll('tbody tr')).toHaveLength(1)
    await search.setValue('no-match')
    expect(w.get('[data-testid="select-visible-models"]').attributes('disabled')).toBeDefined()
    await search.setValue('')
    expect(w.findAll('input[type="checkbox"]').every(input => (input.element as HTMLInputElement).checked)).toBe(true)
    await w.get('[data-testid="bulk-mode"]').setValue('deny')
    await w.get('[data-testid="bulk-model-form"]').trigger('submit')
    await w.get('#user-model-policy-form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(7, 4, [initial().rules[0],
      { model: 'gpt-5.6-luna', mode: 'deny', request_limit: 0, window_hours: 0, window_mode: 'daily' },
      { model: 'gpt-6-astra', mode: 'deny', request_limit: 0, window_hours: 0, window_mode: 'daily' }])
    expect(mocks.candidates).toHaveBeenCalledTimes(1)
  })
  it('saves one user policy with revision and never implicitly activates the site', async () => {
    const w = mount(UserModelPolicyModal, { props: { show: true, user: { id: 7, email: 'example@example.com' } as AdminUser } })
    await flushPromises()
    await w.get('#user-model-policy-form').trigger('submit')
    await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(7, 4, initial().rules)
    expect(mocks.activate).not.toHaveBeenCalled()
    expect(w.text()).toContain('admin.users.modelPolicy.draftHint')
    expect(mocks.success).toHaveBeenCalledWith('admin.users.modelPolicy.draftSaved')
    expect(w.emitted('close')).toBeUndefined()
  })
  it('shows saving state, prevents duplicate writes, and keeps saved rules open for verification', async () => {
    let finish!: (value: ReturnType<typeof initial>) => void
    mocks.get.mockResolvedValue({ ...initial(), enabled: true })
    mocks.save.mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
    const w = mount(UserModelPolicyModal, { props: { show: true, user: { id: 7 } as AdminUser } })
    await flushPromises()
    expect(w.get('[data-testid="bulk-model-form"] button[type="submit"]').classes()).toContain('btn-primary')
    await w.get('#user-model-policy-form').trigger('submit')
    const save = w.get('button[form="user-model-policy-form"]')
    expect(save.text()).toBe('common.saving')
    expect(save.attributes('aria-busy')).toBe('true')
    expect(save.attributes('disabled')).toBeDefined()
    expect(w.emitted('close')).toBeUndefined()
    expect(mocks.success).not.toHaveBeenCalled()
    await w.get('#user-model-policy-form').trigger('submit')
    expect(mocks.save).toHaveBeenCalledTimes(1)
    finish({ ...initial(), enabled: true, revision: 5 }); await flushPromises()
    expect(mocks.success).toHaveBeenCalledWith('admin.users.modelPolicy.saved')
    expect(w.emitted('close')).toBeUndefined()
    expect(save.attributes('aria-busy')).toBe('false')
    expect(w.find('#user-model-policy-form').exists()).toBe(true)
    await w.get('#user-model-policy-form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenLastCalledWith(7, 5, initial().rules)
  })
  it('keeps edits and the dialog on save failure with a visible error and no success notice', async () => {
    mocks.save.mockRejectedValueOnce(new Error('Save conflict; reload the latest rules'))
    const w = mount(UserModelPolicyModal, { props: { show: true, user: { id: 7 } as AdminUser } })
    await flushPromises()
    await w.get('tbody input[aria-label="admin.users.modelPolicy.requests"]').setValue(27)
    await w.get('#user-model-policy-form').trigger('submit'); await flushPromises()
    expect(w.get('[role="alert"]').text()).toContain('Save conflict')
    expect(mocks.error).toHaveBeenCalledWith('Save conflict; reload the latest rules')
    expect(mocks.success).not.toHaveBeenCalled()
    expect(w.emitted('close')).toBeUndefined()
    expect((w.get('tbody input').element as HTMLInputElement).value).toBe('27')
    expect(w.get('button[form="user-model-policy-form"]').text()).toBe('common.save')
    expect(w.get('button[form="user-model-policy-form"]').attributes('disabled')).toBeUndefined()
  })
  it('allows an empty policy without a deny-all confirmation', async () => {
    mocks.get.mockResolvedValue({ ...initial(), rules: [] })
    const w = mount(UserModelPolicyModal, { props: { show: true, user: { id: 7 } as AdminUser } })
    await flushPromises(); await w.get('#user-model-policy-form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(7, 4, [])
    expect(w.find('[data-test="confirm"]').exists()).toBe(false)
  })
  it('confirms removal of existing restrictions', async () => {
    const w = mount(UserModelPolicyModal, { props: { show: true, user: { id: 7 } as AdminUser } })
    await flushPromises()
    await w.get('tbody button.text-red-600').trigger('click')
    await w.get('#user-model-policy-form').trigger('submit'); await flushPromises()
    expect(mocks.save).not.toHaveBeenCalled()
    expect(w.get('[data-test="confirm"]').text()).toContain('admin.users.modelPolicy.clearConfirm')
    await w.get('[data-test="confirm"] button').trigger('click'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(7, 4, [])
  })
  it('adds checked models together with daily limits, then saves independent rules', async () => {
    mocks.get.mockResolvedValue({ ...initial(), rules: [] })
    const w = mount(UserModelPolicyModal, { props: { show: true, user: { id: 7 } as AdminUser } })
    await flushPromises()
    expect(w.findAll('input[type="checkbox"]').map(input => input.attributes('value'))).toEqual(['gpt-5.6-luna', 'gpt-5.6-sol'])
    for (const input of w.findAll('input[type="checkbox"]')) await input.setValue(true)
    expect(w.get('button[form="user-model-policy-form"]').attributes('disabled')).toBeDefined()
    await w.get('#user-model-policy-form').trigger('submit')
    expect(mocks.save).not.toHaveBeenCalled()
    expect(w.find('[role="alert"]').exists()).toBe(false)
    await w.get('[data-testid="bulk-limit"]').setValue(10)
    expect(w.find('[data-testid="bulk-hours"]').exists()).toBe(false)
    expect(w.text()).toContain('admin.users.modelPolicy.dailyReset')
    await w.get('[data-testid="bulk-model-form"]').trigger('submit'); await flushPromises()
    expect(mocks.save).not.toHaveBeenCalled()
    expect(w.findAll('tbody tr')).toHaveLength(2)
    expect(w.findAll('input[type="checkbox"]')).toHaveLength(0)
    expect(w.get('button[form="user-model-policy-form"]').attributes('disabled')).toBeUndefined()
    await w.findAll('tbody input[aria-label="admin.users.modelPolicy.requests"]')[0]!.setValue(20)
    await w.get('#user-model-policy-form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(7, 4, [
      { model: 'gpt-5.6-luna', mode: 'limited', request_limit: 20, window_hours: 0, window_mode: 'daily' },
      { model: 'gpt-5.6-sol', mode: 'limited', request_limit: 10, window_hours: 0, window_mode: 'daily' }
    ])
  })
  it('preserves existing rules, supports hourly batches and rejects invalid quotas', async () => {
    const w = mount(UserModelPolicyModal, { props: { show: true, user: { id: 7 } as AdminUser } })
    await flushPromises()
    expect(w.findAll('input[type="checkbox"]').map(input => input.attributes('value'))).toEqual(['gpt-5.6-luna'])
    await w.get('input[type="checkbox"]').setValue(true)
    await w.get('[data-testid="bulk-cycle"]').setValue('hours')
    await w.get('[data-testid="bulk-model-form"]').trigger('submit'); await flushPromises()
    expect(w.findAll('tbody tr')).toHaveLength(1)
    expect(w.get('[role="alert"]').text()).toContain('admin.users.modelPolicy.invalid')
    await w.get('[data-testid="bulk-limit"]').setValue(15)
    await w.get('[data-testid="bulk-hours"]').setValue(6)
    await w.get('[data-testid="bulk-model-form"]').trigger('submit'); await flushPromises()
    await w.get('#user-model-policy-form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(7, 4, [initial().rules[0], { model: 'gpt-5.6-luna', mode: 'limited', request_limit: 15, window_hours: 6, window_mode: 'hours' }])
  })
  it('rejects batches above 200 rules without partially adding them', async () => {
    mocks.candidates.mockResolvedValue(Array.from({ length: 201 }, (_, i) => `model-${i}`))
    mocks.get.mockResolvedValue({ ...initial(), rules: [] })
    const w = mount(UserModelPolicyModal, { props: { show: true, user: { id: 7 } as AdminUser } })
    await flushPromises()
    await w.get('[data-testid="select-visible-models"]').trigger('click')
    await w.get('[data-testid="bulk-mode"]').setValue('deny')
    await w.get('[data-testid="bulk-model-form"]').trigger('submit'); await flushPromises()
    expect(w.findAll('tbody tr')).toHaveLength(0)
    expect(w.get('[role="alert"]').text()).toContain('admin.users.modelPolicy.invalid')
    expect(mocks.save).not.toHaveBeenCalled()
  })
  it('does not enable editing when the catalog fails', async () => {
    mocks.candidates.mockRejectedValue(new Error('Catalog unavailable'))
    const w = mount(UserModelPolicyModal, { props: { show: true, user: { id: 7 } as AdminUser } })
    await flushPromises()
    expect(w.get('[role="alert"]').text()).toContain('Catalog unavailable')
    expect(w.get('button[type="submit"]').attributes('disabled')).toBeDefined()
    expect(w.find('form').exists()).toBe(false)
  })
  it('preserves saved models absent from the catalog with a warning', async () => {
    mocks.candidates.mockResolvedValue(['gpt-5.6-luna'])
    const w = mount(UserModelPolicyModal, { props: { show: true, user: { id: 7 } as AdminUser } })
    await flushPromises()
    expect(w.text()).toContain('admin.users.modelPolicy.unlistedModel')
    expect(w.getComponent(Select).props('options')).toContainEqual({ value: 'gpt-5.6-sol', label: 'gpt-5.6-sol', disabled: true })
    await w.get('#user-model-policy-form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(7, 4, initial().rules)
  })
  it('ignores a stale load when switching users', async () => {
    let finish!: (value: ReturnType<typeof initial>) => void
    mocks.get.mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
    const w = mount(UserModelPolicyModal, { props: { show: true, user: { id: 7 } as AdminUser } })
    mocks.get.mockResolvedValueOnce({ ...initial(), revision: 8, rules: [{ model: 'gpt-5.6-luna', mode: 'unlimited', request_limit: 0, window_hours: 0 }] })
    await w.setProps({ user: { id: 8 } as AdminUser }); await flushPromises()
    finish(initial()); await flushPromises()
    expect(w.getComponent(Select).props('modelValue')).toBe('gpt-5.6-luna')
  })
})
